version: '3'
services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
