spring:
  application:
    name: autoapp
  main:
    log-startup-info: false
server:
  port: 8080

coinbaseWebSocketUri: wss://ws-feed.pro.coinbase.com
coinbaseApiUri: https://api.pro.coinbase.com/orders
