aws:
  region: us-east-1
  dynamodb:
    endpoint: http://localhost:4566
#
#coinbaseWebSocketUri: wss://ws-feed-public.sandbox.pro.coinbase.com
#coinbaseApiUri: https://api-public.sandbox.pro.coinbase.com

coinbaseWebSocketUri: wss://ws-feed.pro.coinbase.com
coinbaseApiUri: https://api.pro.coinbase.com/orders
