spring:
  application:
    name: autoapp
  main:
    log-startup-info: false
  cache:
    cache-names: coinbaseClient
    caffeine:
      spec: maximumSize=500,expireAfterWrite=24h
  port: 8080
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

logging.file: /var/app/current/auto-app.log
logging.level.root: INFO

management:
  endpoints.web.exposure.include: info, health, metrics, env, beans, loggers
  endpoint.health.show-details: always

resilience4j.ratelimiter:
  instances:
    coinbaseClient:
      limitForPeriod: 3
      limitRefreshPeriod: 1s
      timeoutDuration: 1s

coinbaseWebSocketUri: wss://ws-feed.pro.coinbase.com
coinbaseApiUri: https://api.pro.coinbase.com

graphql:
  tools:
    schema-location-pattern: "**/*.graphqls"
    introspection-enabled: true
  servlet:
    enabled: true
    mapping: /graphql
    cors-enabled: true
    cors:
      allowed-origins: https://kiro.javi-autoapp.com
      allowed-methods: GET, HEAD, POST
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    async-mode-enabled: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.13.0
  props:
    variables:
      editorTheme: "solarized light"
