spring:
  application:
    name: autoapp
  main:
    log-startup-info: false
  cache:
    cache-names: coinbaseClient
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s
  port: 8080
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

management:
  endpoints.web.exposure.include: info, health, metrics, env, beans, loggers
  endpoint.health.show-details: always
logging:
  config: classpath:logback-spring.xml

resilience4j.ratelimiter:
  instances:
    coinbaseClient:
      limitForPeriod: 3
      limitRefreshPeriod: 1s
      timeoutDuration: 1s

coinbaseWebSocketUri: wss://ws-feed.pro.coinbase.com
coinbaseApiUri: https://api.pro.coinbase.com/orders
